name: sida_drivers_app
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #firebase: ^9.0.1
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  firebase_database: ^4.1.1
  firebase_auth_web: ^0.3.1+1
  flutter_svg: ^0.21.0+1
  hexcolor: ^2.0.5
  intl_phone_field: ^1.4.4
  imagebutton: ^0.0.6
  pin_code_fields: ^7.3.0
  adobe_xd: ^2.0.0+1
  flutter_polyline_points: ^0.2.4
  google_maps_place_picker:
  google_maps_flutter: ^1.0.1
  geolocator: ^6.0.0+4
  permission_handler: ^5.0.1+1
  provider: ^4.0.1
  google_maps_webservice: ^0.0.16
  tuple: ^1.0.3
  http: ^0.12.0+4
  rate_my_app: ^0.7.2
  flutter_rating_bar: ^4.0.0
  shared_preferences: ^0.5.12+4
  dotted_line: ^3.0.0
  rolling_switch: ^0.0.2
  flutter_geofire: ^2.0.0


dependency_overrides:
 intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lang/en.json
    - assets/lang/ar.json

  fonts:
    - family: Spoqa Han Sans Neo
      fonts:
        - asset: assets/fonts/SpoqaHanSansNeo-Regular.ttf
        - asset: assets/fonts/SpoqaHanSansNeo-Bold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
